repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: "5.6.4"
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        exclude: "^(django/|builder/src/[a-z]+/vendor/)"
