version: "3.8"

x-django-service: &django-service
  build:
    context: .
    dockerfile: ./Dockerfile
  environment:
    CELERY_BROKER_URL: "pyamqp://django:django@rabbitmq/django"
  env_file:
    - .env
  depends_on:
    - db
    - redis
    - rabbitmq
  volumes:
    - django-data:/app/var
    - ./django:/app
    - built-static:/app/static_built:ro

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.4-alpine3.9
    command: --maxmemory 200mb --maxmemory-policy allkeys-lru

  adminer:
    image: adminer:4.7.5
    ports:
      - 127.0.0.1:8080:8080

  rabbitmq:
    image: rabbitmq:3.8.9
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: django
      RABBITMQ_DEFAULT_PASS: django
      RABBITMQ_DEFAULT_VHOST: django

  django:
    <<: *django-service
    ports:
      - 127.0.0.1:80:8000

  django-worker:
    <<: *django-service
    entrypoint: watchmedo
    command: >
      auto-restart --patterns="*.py" --ignore-directories --recursive -d ./ --
      celery -A thunderstore.core worker -l INFO

  django-beat:
    <<: *django-service
    entrypoint: watchmedo
    command: >
      auto-restart --patterns="*.py" --ignore-directories --recursive -d ./ --
      celery -A thunderstore.core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

  builder:
    build:
      context: .
      dockerfile: ./docker/builder.Dockerfile
    volumes:
      - built-static:/home/node/app/build
      - ./builder/src:/home/node/app/src:ro
      - ./builder/gulpfile.js:/home/node/app/gulpfile.js:ro

volumes:
  db-data:
  django-data:
  built-static:
