version: "3.8"

x-django-services: &django-service
  build:
    context: .
    dockerfile: .devcontainer/django.Dockerfile
  volumes:
    - .:/workspace:ro

services:
  django:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - built-static:/workspace/django/static_built:ro
      - .:/workspace

  django-worker:
    <<: *django-service
    command: bash /workspace/.devcontainer/celeryCommand.sh celeryworker
  django-beat:
    <<: *django-service
    command: bash /workspace/.devcontainer/celeryCommand.sh celerybeat
